# Generated by Django 3.1.7 on 2021-11-18 04:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=256, null=True)),
                ('GST', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('invoice_number', models.BigIntegerField(blank=True, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Client Profile',
            },
        ),
        migrations.CreateModel(
            name='our_billing_address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=256, null=True)),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('bank', models.CharField(blank=True, max_length=256, null=True)),
                ('branch', models.CharField(blank=True, max_length=256, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Our Billing Address',
            },
        ),
        migrations.CreateModel(
            name='our_office_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Inwoin | Office Location', max_length=256, null=True)),
                ('GST_IN', models.CharField(blank=True, max_length=256, null=True)),
                ('office_addresss', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Our Office Location',
            },
        ),
        migrations.CreateModel(
            name='product_and_services_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('HSN_SAC', models.BigIntegerField(blank=True, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('applicable_GST', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_namePASP', to='invoiceApp.client_profile')),
            ],
            options={
                'verbose_name_plural': 'Product And Services Profile',
            },
        ),
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Price', max_length=256, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
                ('product_and_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_and_serviceP', to='invoiceApp.product_and_services_profile')),
            ],
            options={
                'verbose_name_plural': 'Price',
            },
        ),
        migrations.CreateModel(
            name='billing_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Billing Info', max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
                ('amount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amountBI', to='invoiceApp.price')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientBI', to='invoiceApp.client_profile')),
                ('our_billing_add', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_billing_addBI', to='invoiceApp.our_billing_address')),
            ],
            options={
                'verbose_name_plural': 'Billing Info',
            },
        ),
    ]
