# Generated by Django 3.1.7 on 2021-11-18 05:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billed_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Price', max_length=256, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Billed Product',
            },
        ),
        migrations.CreateModel(
            name='invoice_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=256, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('payment completed', 'Payment Completed'), ('payment pending', 'Payment Pending'), ('partial payment pending', 'Partial Payment Pending'), ('not initiated', 'Not Initiated')], default='not initiated', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Inoice Details',
            },
        ),
        migrations.RemoveField(
            model_name='price',
            name='product_and_service',
        ),
        migrations.RenameField(
            model_name='product_and_services_profile',
            old_name='HSN_SAC',
            new_name='HSN',
        ),
        migrations.RemoveField(
            model_name='client_profile',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='client_profile',
            name='invoice_date',
        ),
        migrations.RemoveField(
            model_name='client_profile',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='product_and_services_profile',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='product_and_services_profile',
            name='quantity',
        ),
        migrations.DeleteModel(
            name='billing_info',
        ),
        migrations.DeleteModel(
            name='our_billing_address',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientID', to='invoiceApp.client_profile'),
        ),
        migrations.AddField(
            model_name='invoice_details',
            name='our_office_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_infoID', to='invoiceApp.our_office_location'),
        ),
        migrations.AddField(
            model_name='billed_product',
            name='product_and_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_and_serviceP', to='invoiceApp.product_and_services_profile'),
        ),
    ]
