# Generated by Django 3.1.7 on 2021-11-18 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0002_auto_20211118_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_details',
            name='title',
            field=models.CharField(blank=True, default='Invoice Details', max_length=256, null=True),
        ),
    ]
