# Generated by Django 3.1.7 on 2021-11-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0003_invoice_details_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='billed_product',
            name='invoice_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_infoBP', to='invoiceApp.invoice_details'),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='product_and_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_and_serviceBP', to='invoiceApp.product_and_services_profile'),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='title',
            field=models.CharField(blank=True, default='Billed Products', max_length=256, null=True),
        ),
    ]
