# Generated by Django 3.1.7 on 2021-11-18 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0004_auto_20211118_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_and_services_profile',
            name='applicable_GST',
        ),
        migrations.AddField(
            model_name='billed_product',
            name='applicable_GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='billed_product',
            name='invoice_Type_options',
            field=models.CharField(choices=[('interstate', 'Interstate'), ('intrastate', 'Intrastate')], default='interstate', max_length=256),
        ),
    ]
