# Generated by Django 3.1.7 on 2021-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0005_auto_20211118_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice_details',
            options={'verbose_name_plural': 'Invoice Details'},
        ),
        migrations.RemoveField(
            model_name='billed_product',
            name='invoice_Type_options',
        ),
        migrations.AddField(
            model_name='billed_product',
            name='invoice_options',
            field=models.CharField(choices=[('interstate', 'Interstate'), ('intrastate', 'Intrastate')], default='interstate', max_length=256),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
