# Generated by Django 3.1.7 on 2021-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0006_auto_20211118_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billed_product',
            name='invoice_options',
        ),
        migrations.AddField(
            model_name='billed_product',
            name='invoice_type',
            field=models.CharField(choices=[('interstate', 'Interstate'), ('intrastate', 'Intrastate')], default='interstate', max_length=256),
        ),
    ]
