# Generated by Django 3.2.7 on 2021-12-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0010_auto_20211119_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billed_product',
            old_name='invoice_type',
            new_name='GST_type',
        ),
        migrations.AddField(
            model_name='billed_product',
            name='price_per_product',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
