# Generated by Django 3.2.7 on 2021-12-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0011_auto_20211210_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed_product',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='applicable_GST_amount_plus_GST',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='price_per_product',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
