# Generated by Django 3.2.7 on 2021-12-11 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0014_city_country_pin_code_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(blank=True, max_length=256, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=256, null=True)),
                ('country_name', models.CharField(blank=True, max_length=256, null=True)),
                ('state_name', models.CharField(blank=True, max_length=256, null=True)),
                ('city_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('pincode', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Address List',
            },
        ),
        migrations.DeleteModel(
            name='address_line1',
        ),
        migrations.DeleteModel(
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='city',
            name='state',
        ),
        migrations.DeleteModel(
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='country',
        ),
        migrations.DeleteModel(
            name='city',
        ),
        migrations.DeleteModel(
            name='country',
        ),
        migrations.DeleteModel(
            name='state',
        ),
    ]
