# Generated by Django 3.2.7 on 2021-12-11 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0015_auto_20211211_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_office_location',
            name='addresses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressesOOL', to='invoiceApp.address'),
        ),
    ]
