# Generated by Django 3.2.7 on 2021-12-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0016_our_office_location_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_office_location',
            old_name='addresses',
            new_name='address',
        ),
    ]
