# Generated by Django 3.2.7 on 2021-12-11 10:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0017_rename_addresses_our_office_location_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_bank_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=256, null=True)),
                ('account_number', models.BigIntegerField(blank=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=256, null=True)),
                ('branch', models.CharField(blank=True, max_length=256, null=True)),
                ('IFSC_code', models.CharField(blank=True, max_length=50, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Our Bank Details',
            },
        ),
        migrations.CreateModel(
            name='Terms_and_conditions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terms_and_condition', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Terms And Conditions',
            },
        ),
        migrations.RemoveField(
            model_name='our_office_location',
            name='title',
        ),
        migrations.AddField(
            model_name='our_office_location',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ourOfficeLocation/Image/'),
        ),
        migrations.AddField(
            model_name='our_office_location',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='ourOfficeLocation/signature/'),
        ),
        migrations.AddField(
            model_name='our_office_location',
            name='bank_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_detailsOOL', to='invoiceApp.our_bank_details'),
        ),
    ]
