# Generated by Django 3.2.7 on 2021-12-11 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0019_our_office_location_terms_and_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terms_and_conditions',
            old_name='Terms_and_condition',
            new_name='terms_and_condition',
        ),
    ]
