# Generated by Django 3.2.7 on 2021-12-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0020_rename_terms_and_condition_terms_and_conditions_terms_and_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='our_office_location',
            old_name='Terms_and_condition',
            new_name='terms_and_condition',
        ),
    ]
