# Generated by Django 3.2.7 on 2021-12-11 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0021_rename_terms_and_condition_our_office_location_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_and_services_profile',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
