# Generated by Django 3.2.7 on 2021-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0022_product_and_services_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billed_product',
            name='GST_type',
        ),
        migrations.AlterField(
            model_name='product_and_services_profile',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
