# Generated by Django 3.2.7 on 2021-12-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0023_auto_20211211_1905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terms_and_conditions',
            options={'verbose_name_plural': 'Our Terms And Conditions'},
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addessCP', to='invoiceApp.address'),
        ),
    ]
