# Generated by Django 3.2.7 on 2021-12-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0024_auto_20211211_2012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Our Address List'},
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
