# Generated by Django 3.2.7 on 2021-12-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0025_auto_20211211_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressCP', to='invoiceApp.address'),
        ),
    ]
