# Generated by Django 3.2.7 on 2021-12-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0026_alter_client_profile_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address List'},
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='address',
            name='city_Name',
            field=models.CharField(max_length=256),
        ),
    ]
