# Generated by Django 3.2.7 on 2021-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0027_auto_20211211_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_bank_details',
            name='IFSC_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='account_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='account_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='bank_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='branch',
            field=models.CharField(max_length=256),
        ),
    ]
