# Generated by Django 3.2.7 on 2021-12-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0028_auto_20211211_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms_and_conditions',
            name='terms_and_condition',
            field=models.TextField(),
        ),
    ]
