# Generated by Django 3.2.7 on 2021-12-11 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0030_auto_20211211_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billed_product',
            name='applicable_GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='invoice_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_infoBP', to='invoiceApp.invoice_details'),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='price_per_product',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='product_and_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_and_serviceBP', to='invoiceApp.product_and_services_profile'),
        ),
        migrations.AlterField(
            model_name='billed_product',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='GST',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressCP', to='invoiceApp.address'),
        ),
        migrations.AlterField(
            model_name='client_profile',
            name='client_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientID', to='invoiceApp.client_profile'),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='invoice_details',
            name='our_office_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='our_infoID', to='invoiceApp.our_office_location'),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='IFSC_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='account_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='account_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='bank_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='our_bank_details',
            name='branch',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='our_office_location',
            name='GST_IN',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='our_office_location',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addressesOOL', to='invoiceApp.address'),
        ),
        migrations.AlterField(
            model_name='our_office_location',
            name='company_name',
            field=models.CharField(blank=True, default='Inwoin Technologies Pvt Ltd.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='our_office_location',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='product_and_services_profile',
            name='HSN',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_and_services_profile',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='terms_and_conditions',
            name='terms_and_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
