# Generated by Django 3.2.7 on 2021-12-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0032_auto_20211211_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city_Name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state_name',
            field=models.CharField(max_length=256),
        ),
    ]
