# Generated by Django 3.2.7 on 2021-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0033_auto_20211211_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='our_office_location',
            name='mobile_number',
            field=models.BigIntegerField(),
        ),
    ]
