# Generated by Django 3.2.7 on 2021-12-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0034_alter_our_office_location_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice_details',
            name='invoice_number',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='our_office_location',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
