# Generated by Django 3.2.7 on 2021-12-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0038_alter_address_state_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='city_names',
            new_name='city_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city_Name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state_name',
        ),
    ]
