# Generated by Django 3.2.7 on 2021-12-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceApp', '0039_auto_20211213_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_and_services_profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
